# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-24 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busca',
            old_name='text',
            new_name='email',
        ),
    ]
